name: SonarCloud scan

# Specify when the Action should be triggered: when a pull request is opened against the 'devel' or 'master' branch
on:
  pull_request:
    branches: [devel, master]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: SonarCloud Scan
        run: |
            sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=i2pc -Dsonar.login=$SONAR_TOKEN
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
