name: Generate tag
on:
  # Will trigger when changes are pushed to master
  push:
    branches: [ master ]

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@main
    
    # Get package version and tag
    - name: Get version and tag
      run: |
        export PACKAGE_VERSION=$(./xmipp version --short)
        git tag $PACKAGE_VERSION
        git push origin $PACKAGE_VERSION
