# Initial code obtained from https://gist.github.com/cicirello/ade1d559a89104140557389365154bc1#file-major-release-tag-yml

name: Update Major Release Tag

on:
  release:
    types: [created]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get major version number and update tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        MAJOR=${VERSION%%.*}
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'action@github.com'
        git tag -fa "${MAJOR}" -m 'Update major version tag'
        git push origin "${MAJOR}" --force
